version: "3.8"

services:
  pg:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - pg:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg: